### Get all users
GET http://localhost:8080/users
Accept: application/json

### Create a new user
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": "1",
  "name": "John Doe",
  "email": "john.doe@example.com"
}

### Get user by ID
GET http://localhost:8080/users/1
Accept: application/json

### Update user by ID
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "id": "1",
  "name": "John Doe Updated",
  "email": "john.updated@example.com"
}

### Delete user by ID
DELETE http://localhost:8080/users/1
